version: '3'

services:
  nginx-rtmp:
    build: nginx-server/
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ${PWD}/nginx-server/confs/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx-server/logs:/var/log/nginx
      - ${PWD}/nginx-server:/app
    restart: always

  fastapi:
    build:
      context: service
      dockerfile: Dockerfile_cpu
    ports:
      - 81:80
      - 5000:5000
    volumes:
      - ${PWD}/service/src:/opt
      #- ${PWD}/service/serialization.py:/usr/local/lib/python3.6/site-packages/torch/serialization.py
      #- type: bind
      #  source: ${PWD}/service/serialization.py
      #  target: /usr/local/lib/python3.6/site-packages/torch/serialization.py
      #  read_only: true
    restart: always
