version: '3'

services:
  nginx-rtmp:
    build: nginx-server/
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ${PWD}/nginx-server/confs/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx-server/logs:/var/log/nginx
      - ${PWD}/nginx-server:/app

  fastapi:
    build:
      context: server
      dockerfile: Dockerfile_cpu
    ports:
      - 81:80
      - 5000:5000
    volumes:
      - ${PWD}/service/src:/opt
