version: '3'

services:
  nginx-rtmp:
    image: nginx-rtmp
    # build: nginx-server/
    depends_on:
      - rabbitmq
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ${PWD}/nginx-server/confs/nginx.conf:/etc/nginx/nginx.conf.template
      - ${PWD}/nginx-server/logs:/var/log/nginx
      - ${PWD}/nginx-server:/app
    restart: always

  fastapi:
    image: fastapi_service
    #build:
      #context: service
      #dockerfile: Dockerfile_cpu
    container_name:
      fastapi
    depends_on:
      - rabbitmq
    ports:
      - 81:80
      - 5000:5000
    volumes:
      - ${PWD}/service/src:/opt
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
