version: '3'

services:
  nginx-rtmp:
    build: nginx-server/
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ${PWD}/nginx-server/confs/nginx.conf:/etc/nginx/nginx.conf.template
      - ${PWD}/nginx-server/logs:/var/log/nginx
      - ${PWD}/nginx-server:/app
    restart: always

  fastapi:
    build:
      context: service
      dockerfile: Dockerfile_cpu
    container_name:
      fastapi
    ports:
      - 81:80
      - 5000:5000
    volumes:
      - ${PWD}/service/src:/opt
    restart: always
