version: '3'

services:
  nginx-rtmp:
    build: nginx-server/
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - /root/project/nginx-server/confs/nginx.conf:/etc/nginx/nginx.conf
      - /root/project/nginx-server/logs:/var/log/nginx
      - /root/project/nginx-server:/app
